name: release-gggpay

on:
  push:
    branches:
      - release-gggpay

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install NPM packages
        run: npm install
      

      - name: Set environment variables
        run: |
          echo "ENV_BRAND=GGGPAY" >> $GITHUB_ENV
          echo "ENV_DOMAIN=gggpay.org" >> $GITHUB_ENV
          echo "ENV_EMAIL=support@gggpay.org" >> $GITHUB_ENV
          echo "ENV_LOGO=gggpay.png" >> $GITHUB_ENV

      - name: Build project
        run: npm run build

      - name: login s3
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.S3_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: push to bucket
        run: aws s3 sync ./build s3://doc.gggpay.org